### ISSUE TITLE
KeenSwiftClientExample needs to be updated to conform to changes in Swift 2

### ISSUE THREAD

**Issue by terryhorner** [keenlabs/KeenClient-iOS#132]
There are a bunch of failures due to the changes in Swift 2 that need to be cleaned up. Using `Edit > Convert > To Latest Swift Syntax` cleans up most of them, but `countQueryCompleted` in `ThirdViewController.swift` also needs to be cleaned up a bit based on the removal of `error` from `NSJSONSerialization.JSONObjectWithData`.

**Comment by wetzler** [comment]
We got this feedback from a user today:

"Totally love your product guys. I just had little bit troubles with documentation for your iOS SDK. Since Swift 2.0 you have there some issues in wording and syntax. I had to dig directly to your library in order to get the right name of method. Also error handling changed in the Swift 2.0. But I was able to make it working. I didn't want to create a pull request for your documentation, since I'm not super proficient in iOS development.

Since I integrated it, everything seems to be working fine so far:)"
